- 
  title: Project Assistant
  organization: Samsung Student Ecosystem for Engineered Data (SEED) Lab, Karnataka
  years: 2020-2021
  url: https://news.samsung.com/in/samsung-sets-up-a-world-class-artificial-intelligence-machine-learning-data-engineering-lab-jointly-with-kle-tech-university
  description:
    - Proposed projects for Lab at KLE Tech Univeristy.
- 
  title: Director of Resource Management 
  organization: Rotract Regency Of NSIT
  years: 2015-2018
  url: http://www.nsit.ac.in/student-facilities/societies/community-service-initiatives/
  description:
    - Organized collection drives, workshops, events like Masoom Duniya, Sadbhavna etc. for children with special abilities. Involved in managing IT and Financial Resources for the team.
  
- title: Mentor
  organization: Google Developer Student Club(GDSC), NSIT
  years: 2017-2018
  url: https://github.com/GDSC-NSIT
  description:
    - Mentored junior students in Android Programming. 